name: Blackduck scan

on:
  push:
    branches:
    - oidc-2

jobs:
  blackduck-codescan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read 
      
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Workflow detail api request
        shell: bash
        run: |
          echo "Ref name is $GITHUB_RUN_ID"
          echo "Source is ${{ github.server_url }}/${{ github.repository }}"
          echo "Subject is $GITHUB_WORKFLOW_REF|${{ github.run_id }}|${{ github.run_attempt }}|${{ github.run_number }}"
          echo "Job is $GITHUB_JOB"
          echo "Step id is ${{ steps.internal.id }}"

      - name: Blackduck scan
        uses: cloudbees-io-gha/black-duck-scan-publish@v2
        with:
          server-url: ${{ vars.BLACKDUCK_SERVER_URL }}
          api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}



