name: grype-scan-publish

on: [workflow_dispatch]

jobs:
  grype-codescan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read  
    outputs:
      grype-job-output-critical: ${{ steps.grype-step.outputs.critical-count }}
      grype-job-output-very-high: ${{ steps.grype-step.outputs.very-high-count }}
      grype-job-output-high: ${{ steps.grype-step.outputs.high-count }}
      grype-job-output-medium: ${{ steps.grype-step.outputs.medium-count }}
      grype-job-output-low: ${{ steps.grype-step.outputs.low-count }}
      
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Print GITHUB_RUN_ID
        run: echo "Ref name is $GITHUB_RUN_ID"

      - name: Create empty JSON file in workspace
        run: |
          FILE_PATH="$GITHUB_WORKSPACE/store/request/request.json"
          mkdir -p "$(dirname "$FILE_PATH")"
          touch "$FILE_PATH"
          echo "File created at: $FILE_PATH"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      # Step 4: Save the Docker image as a TAR file
      - name: Save Docker image as TAR file
        run: |
          docker save -o output.tar myapp:latest
          tar -tf output.tar
          
      - id: grype-step
        name: Grype scan
        uses: cloudbees-io-gha/grype-scan-publish@v1
        with:
          binary-tar-path: output.tar

      - id: print-outputs-from-grype-step
        name: Print outputs from upstream grype step
        shell: bash
        run: |
            #printing all outputs
            echo "Outputs from upstream grype step:"
            echo "Critical Count: ${{steps.grype-step.outputs.critical-count}}"
            echo "Very High Count: ${{steps.grype-step.outputs.very-high-count}}"
            echo "High Count: ${{steps.grype-step.outputs.high-count}}"
            echo "Medium Count: ${{steps.grype-step.outputs.medium-count}}"
            echo "Low Count: ${{steps.grype-step.outputs.low-count}}"