name: Trivy Hybrid Scan

on:
  push:
    branches:
      - oidc-2

jobs:
  trivy-hybrid-scan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read  

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Workflow detail api request
        shell: bash
        run: |
          echo "Ref name is $GITHUB_RUN_ID"
          echo "Source is ${{ github.server_url }}/${{ github.repository }}"
          echo "Subject is $GITHUB_WORKFLOW_REF|${{ github.run_id }}|${{ github.run_attempt }}|${{ github.run_number }}"
          echo "Job is $GITHUB_JOB"
          echo "Step id is ${{ steps.internal.id }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      # Step 4: Save the Docker image as a TAR file
      - name: Save Docker image as TAR file
        run: |
          docker save -o output.tar myapp:latest
          tar -tf output.tar

      - name: Run Trivy scan
        uses: cloudbees-io-gha/trivy-scan-publish@v2
        with:
          binary-tar-path: output.tar
          cloudbees-url: "https://api.saas-qa.beescloud.com"
